export const INIT_ADDRESS = "INIT_ADDRESS";
export const ADDRESS_RESET = "ADDRESS_RESET";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";